### ISSUE TITLE
Getting this issue while installing the webapp according to the steps given in the readme file.

### ISSUE THREAD

**Issue by Regina-Walker** [Wofyy/Frame2File#1]
![image_2024-08-30_185338150](https://github.com/user-attachments/assets/5287b5cf-50fa-47c5-ae24-569b0132835c)

**Comment by Wofyy** [comment]
The installation guide provided in the README is specific to Linux OS. For a Windows-specific installation guide, please try searching for instructions tailored to Windows or adapt the steps accordingly.

**Comment by ninadch06** [comment]
I can update the readme file for both windows and linux os. 
Please do let me know if I can proceed with it.

**Comment by Wofyy** [comment]
sure, you can go ahead with that
