### ISSUE TITLE
'pytesseract' Error on Video Upload.

### ISSUE THREAD

**Issue by finley953** [Wofyy/Frame2File#3]
**Title:** `pytesseract` Error on Video Upload

**Description:**

![image](https://github.com/user-attachments/assets/168bf67e-fb46-4f89-a336-dca6cd007ecf)

I'm experiencing a `pytesseract` error when uploading a video. The setup and installation were successful, and frames are extracted correctly, but the process stops at this error after a few seconds. 

**Steps to Reproduce:**

1. Follow setup instructions.
2. Upload a video.
3. Error occurs after loading.

**Environment:**
- OS: Windows
- Python version: 3.12.3

Any help would be appreciated!

**Comment by Wofyy** [comment]
Thank you for bringing this up. The project was initially developed on a **Linux** system, where _pytesseract_ was installed globally, and the environment handled everything seamlessly.

For **Windows**, things might work a bit differently. You may need to adjust some configurations related to _pytesseract_

**Comment by SAHILGAWLI** [comment]
Thanks for pointing that out, I believe I can address this issue.

**Comment by Wofyy** [comment]
sure, if you can

**Comment by Wofyy** [comment]
Works! Great initiative!
